// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgw61gO4vE2dNVvYuJXe_0TYwhhbquws8',
    appId: '1:385588931571:web:7b7b3c0ab391744c338086',
    messagingSenderId: '385588931571',
    projectId: 'assignment9-36f85',
    authDomain: 'assignment9-36f85.firebaseapp.com',
    storageBucket: 'assignment9-36f85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBdNRttr4xG5EY4c3K1IT2D_GC6nvxg8k',
    appId: '1:385588931571:android:36235d88743817e6338086',
    messagingSenderId: '385588931571',
    projectId: 'assignment9-36f85',
    storageBucket: 'assignment9-36f85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7jjlk3COePKzFctjWc33yn9aO5FUCtQ',
    appId: '1:385588931571:ios:1612aef198e9655d338086',
    messagingSenderId: '385588931571',
    projectId: 'assignment9-36f85',
    storageBucket: 'assignment9-36f85.appspot.com',
    iosBundleId: 'com.example.assignment9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs7jjlk3COePKzFctjWc33yn9aO5FUCtQ',
    appId: '1:385588931571:ios:1612aef198e9655d338086',
    messagingSenderId: '385588931571',
    projectId: 'assignment9-36f85',
    storageBucket: 'assignment9-36f85.appspot.com',
    iosBundleId: 'com.example.assignment9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgw61gO4vE2dNVvYuJXe_0TYwhhbquws8',
    appId: '1:385588931571:web:706e211182e20342338086',
    messagingSenderId: '385588931571',
    projectId: 'assignment9-36f85',
    authDomain: 'assignment9-36f85.firebaseapp.com',
    storageBucket: 'assignment9-36f85.appspot.com',
  );
}
